# MySQL Profile configuration
server.port=8080

# Spring DataSource properties (MySQL)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ticketdesk_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JPA / Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Actuator config
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
