# MySQL Profile configuration
server.port=8080
server.address=0.0.0.0

# Spring DataSource properties (MySQL)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JPA / Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Actuator config
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
